development: &default
  enabled: false
  suffix: '.min'
  selector: '**/*.js'
  repetitive:
    -
      source: 'src/scripts'
      target: 'dist/scripts'


test: &test
  <<: *default

production: &production
  <<: *default
