development: &default
  enabled: true
  minimize: true
  source: 'src/assets/scripts'
  target: 'dist/scripts'
  selector: '**/*.coffee'


test: &test
  <<: *default

production: &production
  <<: *default
